$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: |
  python train.py
code: ./
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
compute: azureml:amlcluster